param(
  [ValidateSet("prod")]
  [string]$Environment = "prod",
  [string]$Region = "us-east-2",
  [switch]$AutoApprove,
  [switch]$SkipBootstrap
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$LocalBin = Join-Path $env:USERPROFILE ".local\bin"
$env:PATH = "$LocalBin;$env:PATH"

function Require-Command {
  param([string]$Name)

  $Command = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $Command) {
    throw "$Name is not available on PATH. Expected it under $LocalBin or installed globally."
  }
}

Require-Command "aws"
Require-Command "terraform"

$env:AWS_REGION = $Region
$env:AWS_DEFAULT_REGION = $Region

Write-Host "Checking AWS credentials..."
$IdentityJson = aws sts get-caller-identity --output json 2>$null
if ($LASTEXITCODE -ne 0 -or -not $IdentityJson) {
  throw "AWS credentials are not configured. Run 'aws configure' first, then verify with 'aws sts get-caller-identity'."
}
$Identity = $IdentityJson | ConvertFrom-Json
Write-Host "AWS account: $($Identity.Account)"
Write-Host "AWS principal: $($Identity.Arn)"
Write-Host ""

if (-not $SkipBootstrap) {
  Write-Host "Bootstrapping Terraform remote state bucket..."
  Push-Location (Join-Path $ProjectRoot "terraform\bootstrap")
  try {
    terraform init
    if ($AutoApprove) {
      terraform apply -auto-approve
    } else {
      terraform apply
    }
  } finally {
    Pop-Location
  }
  Write-Host ""
}

Write-Host "Ensuring Terraform config SSM parameters exist for $Environment..."
$ConfigPrefix = "/ship/terraform-config/$Environment"
aws ssm put-parameter `
  --name "$ConfigPrefix/environment" `
  --value "$Environment" `
  --type String `
  --overwrite `
  --region $Region | Out-Null

$StateBucket = aws ssm get-parameter `
  --name "/ship/terraform-state-bucket" `
  --query "Parameter.Value" `
  --output text `
  --region us-east-1

if (-not $StateBucket) {
  throw "Could not read /ship/terraform-state-bucket from SSM in us-east-1. Run without -SkipBootstrap first."
}

Write-Host "Using Terraform state bucket: $StateBucket"
Write-Host ""

$TfDir = Join-Path $ProjectRoot "terraform\environments\$Environment"
$TfVars = Join-Path $TfDir "terraform.tfvars"

@"
# Auto-generated by scripts/deploy-aws-architecture.ps1
# Do not commit this file.

environment = "$Environment"
aws_region  = "$Region"
"@ | Set-Content -Path $TfVars -Encoding UTF8

Push-Location $TfDir
try {
  Write-Host "Initializing Terraform for $Environment in $Region..."
  terraform init -backend-config="bucket=$StateBucket" -reconfigure

  Write-Host ""
  Write-Host "Planning architecture..."
  terraform plan -var="aws_region=$Region" -out=tfplan

  Write-Host ""
  Write-Host "Applying architecture..."
  if ($AutoApprove) {
    terraform apply -auto-approve tfplan
  } else {
    terraform apply tfplan
  }

  Write-Host ""
  Write-Host "Architecture outputs:"
  terraform output
} finally {
  Pop-Location
}
